### ISSUE TITLE
German Umlauts and Eszett (ä, ö, ü, ß) not displayed in addresses

### ISSUE THREAD

**Issue by kyoforkshomebrews** [woheller69/lavatories#14]
**Describe the bug**
In the addresses you can see umlauts and ß being replaced with a question mark symbol:

**How to Reproduce**
1. Add a German speaking city
2. Go to "toilets" 
3. Check addresses to see that umlauts and ß are replaced by question mark symbols 

**Expected behavior**
ä, ö, ü, ß are displayed

**Screenshots**
![Screenshot_20230827_193945_org woheller69 lavatories](https://github.com/woheller69/lavatories/assets/49304418/c4bde988-11ff-4074-8334-17c0fb99f901)

**Environment (please complete the following information):**
 - App version: 1.9
 - Android version: 10
 - Device: Huawei P Smart 2019 (POT_LX1)

**Comment by woheller69** [comment]
Obviously they changed their API again.
I recently changed my code because suddenly addresses weren't shown correctly anymore.
It seems they reverted the change - so here is a version where I also reverted my change.

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/12448597/app-release.apk.zip)

**Comment by woheller69** [comment]
Probably has to do with this change at Nominatim:
https://github.com/osm-search/Nominatim/pull/3167/commits/a9edd57fe28021e3526e6787a43eda4dd3b84125

https://github.com/woheller69/lavatories/releases/tag/V2.1
